name: 'The Kimbrell Firm, P.C.'
favicon: null
layout_spectrum: 0.1726781614124775
typography_spectrum: 0.3052828595973551
title: 'Atlanta DUI Attorney and Georgia Criminal Defense '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4769717385061085
  lightness: 0.5610995423048735
  saturation: 0.04368623276241124
  rhythmicContrast: 0.4291478907689452
purpose: []
